### PR TITLE
Cleanup before releasing 1.0.0

### LINKED ISSUE #69: Request: make RegisterToApiLayer part of zowe commons
We have code in our service that registers to the API layer. We modeled it after the provided sample:

https://github.com/zowe/sample-spring-boot-api-service/blob/master/zowe-rest-api-sample-spring/src/main/java/org/zowe/sample/apiservice/zowe/RegisterToApiLayer.java

Would it be possible (or make sense) to include this with Zowe commons jar?

### PR DESCRIPTION
**Pull request by plavjanik**
This PR does the following:
- Sets Apache 2.0 license for the sample application
  - Resolves https://github.com/zowe/sample-spring-boot-api-service/issues/71
- Moves common classes from the sample to the commons library
  - `org.zowe.sample.apiservice.apidoc.ApiDocConstants` moved to `org.zowe.commons.apidoc.ApiDocConstants`
    - You can replace all occurences in your sample by: 
      ```sh
      find . -name '*.java' -print -exec sed 's/org.zowe.sample.apiservice.apidoc.ApiDocConstants./org.zowe.commons.apidoc.ApiDocConstants./g' {} \;
      ```
  - Package `org.zowe.sample.apiservice.zowe` moved to `org.zowe.commons.apiml`
    - Users of the sample need to delete package `org.zowe.sample.apiservice.zowe` that contains class `ApiMediationServiceConfig`
    - Resolves #69 
  - `zowe-rest-api-sample-spring/src/main/java/org/zowe/sample/apiservice/CsrfController.java` → `zowe-rest-api-commons-spring/src/main/java/org/zowe/commons/spring/security/CsrfController.java`
    - Users of the sample should delete existing class `CsrfController.java` from the sample
  - `zowe-rest-api-sample-spring/src/main/java/org/zowe/sample/apiservice/config/WebServerSecurityConfig.java → zowe-rest-api-commons-spring/src/main/java/org/zowe/commons/spring/security/HttpsWebServerConfig.java`
    - Users of the sample should delete existing class `WebServerSecurityConfig.java` from the sample if it has not changed from the original

### CODE REVIEW

**Comment by dkelosky** [comment]
Hi Petr - just wanted to confirm that this PR does not address https://github.com/zowe/sample-spring-boot-api-service/issues/69 - correct?

**Comment by plavjanik** [comment]
> Hi Petr - just wanted to confirm that this PR does not address #69 - correct?

Hi Dan, it addresses #69. I have added list of things that have been done to the description of the PR with instructions that needs to be done. Please review and tell us if this is ok.

**Comment by plavjanik** [comment]
@dkelosky The plan is to release this as `0.9.0` first so we can catch problems to some teams before releasing 1.0.0

**Comment by dkelosky** [comment]
Hi - sorry I wrote my comment incorrectly.  I should not have had "not" in there.  I wanted to confirm because looking at the file changes for the PR - I didn't see it, but I must have overlooked it.  

The instructions look great - we'll try to get this new commons merged into our current API very soon.  

I do have one question I'll take to our internal chat.

Agree on great choice for a PR number 😄

**Comment by plavjanik** [comment]
> Agree on great choice for a PR number 😄

Pure luck! 🍀

**Comment by plavjanik** [comment]
I have tested the APIML integration on our systems manually. I am going to merge it and release 0.9.0.

**Pull request merged**
